test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_square_root (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 27, in test_square_root
    output_exo = list(map(exercice.square_root, self.numbers))
  File "/home/runner/work/c01_ch3_exercice1-totyrola/c01_ch3_exercice1-totyrola/exercice.py", line 7, in square_root
    return math.sqrt ()
TypeError: sqrt() takes exactly one argument (0 given)

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
